version: "3.8"
services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--experimental.plugins.fail2ban.modulename=github.com/tomMoulard/fail2ban"
      - "--experimental.plugins.fail2ban.version=v0.6.6"
      - "--experimental.hub=true"
      - "--accesslog.filepath=/path/to/access.log"
      - "--hub.tls.insecure=true"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - "demo-net"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    build: ./frontend
    image: demo-frontend
    networks:
      - "demo-net"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`demo-frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  backend:
    build: ./backend
    image: demo-backend
    networks:
      - "demo-net"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`demo-backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"

networks:
  demo-net: